### PR TITLE
Added content about STL Vector and some small changes

### PR DESCRIPTION
**Pull request by pra9patil**
Sir As I said added content in the stl section in website and did some minor changes like after cliking on checklist it will not redirecting to the home page it will first redirect to the STL page and then after clicking on it , the home page is open 
I hope you like this change 
will you please merge my PR under hactoberfest23

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
solve merge conflicts

**Comment by pra9patil** [comment]
Screenshot (93)

When I forked repo there is nothing callled javabasics so I think this conflict is resolved by you only .

**Comment by pra9patil** [comment]
Sir will you please accept my PR under hacttoberfest

**Comment by UjjwalSharma01** [comment]
> Screenshot (93)
> 
> When I forked repo there is nothing callled javabasics so I think this conflict is resolved by you only .

Bhai esa nahi hota h , repo ek.baar fork krne ke baad upto date rkhni hoti h with the upstream repo to avoid this
Vaise merge conflicts thik krne ka kaam tumhara h, lemme know agr tumhe nahi aata i will do it for you

**Comment by pra9patil** [comment]
Yes bhaiya do it for me mujhe o nhi samj aa raha ki gadbd ka ho rahi hai

**Comment by pra9patil** [comment]
Thank you so much

**Comment by UjjwalSharma01** [comment]
> Yes bhaiya do it for me mujhe o nhi samj aa raha ki gadbd ka ho rahi hai

Buddy main subha tak krta hu, don't worry bas yahi issue h your PR is accepted 😊

**Comment by pra9patil** [comment]
Thank you Bhaiya

**Comment by UjjwalSharma01** [comment]
> Sir is this issue resolved

issue resolved

**Review by UjjwalSharma01 — APPROVED** [review]

**Pull request merged**
