### PR TITLE
Python basics added and Topics align centered on main page

### PR DESCRIPTION
**Pull request by aditya4567uk**
Python language added
---->Intro to python
---->Variables & Data types [ with examples ]
---->Conditional statements [ with examples ]
---->Functional programming [ with examples ]

Alignment changed to center on main page topics [c++ basics, python basics etc..] for better look and visibility

### CODE REVIEW

**Comment by aditya4567uk** [comment]
if my contributions will be merged i will be contributing to C# programming language on your website.

**Comment by UjjwalSharma01** [comment]
Have you covered all the basics?

**Comment by aditya4567uk** [comment]
> Have you covered all the basics?

Yes basics are covered you can see in test deployment, I'll be adding more to it in coming days.

**Comment by UjjwalSharma01** [comment]
> > Have you covered all the basics?
> 
> Yes basics are covered you can see in test deployment, I'll be adding more to it in coming days. So could you merge? 

- Add Loops
- intro and basic syntax of data structures like list, tuple, dictionary etc.

Also write the code syntax under __code__ tag in html, check GFG for reference

**Comment by aditya4567uk** [comment]
> Python language added ---->Intro to python ---->Variables & Data types [ with examples ] ---->Conditional statements [ with examples ] ---->Functional programming [ with examples ]
> 
> Alignment changed to center on main page topics [c++ basics, python basics etc..] for better look and visibility

I have done a new pull request with updates you have asked #74 kindly look into it and merge. thank you.

**Pull request closed without merging**
