### PR TITLE
css changes made again

### PR DESCRIPTION
**Pull request by deepbeatz**
css changes made to all buttons

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
Resolve merge conflicts @deepbeatz

**Comment by deepbeatz** [comment]
How can I do that?

**Comment by UjjwalSharma01** [comment]
> How can I do that?

Check the conflicting files and edit the file

**Comment by UjjwalSharma01** [comment]
hover effect is not working on buttons please recheck

**Pull request closed without merging**
