### PR TITLE
Added caousel to quotes in index.html

### PR DESCRIPTION
**Pull request by geeky-hypertext629**

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
Instead of the carousel, do not change the current dimensions for the quote, but make it dynamic while adding the functionality that, each time the website reloads it should display a different quote

**Comment by geeky-hypertext629** [comment]
Buddy pls merge it. I have put in a lot of time and effort in it and I am
just a beginner. I don't want the effort to go waste. This is the second
time I have made a pull request. You rejected the first one. I do have
other tasks to do as well I can't just be giving all my time to one repo
all day. Pls understand

Regards
Subham Chandra

**Comment by UjjwalSharma01** [comment]
@geeky-hypertext629 i respect your time and efforts, i know it feels bad when your PR gets rejected that's why you should first create an issue in the issues section of the repo so that maintainer get to know that what you are really doing instead of a direct surprise in the form of PR, i could have merged it but we need to scrap this feature sooner or later, so this is eventually of no use

**Comment by geeky-hypertext629** [comment]
Okay I am adding the new quote on refresh feature. Please merge this time 🙏

**Pull request closed without merging**
