### PR TITLE
fix: Added responsive navigation bar with hamburger menu icon

### LINKED ISSUE #15: Add a Navigation bar
- try to make it responsive
- shift the buttons, Contact Us and Contribute to the navigation bar

### PR DESCRIPTION
**Pull request by kalkeshwar**
fixes #15

These PR will fixes #15 which adds responsive navbar , please review and merge the PR and feel free to update here.

### CODE REVIEW

**Comment by kalkeshwar** [comment]
@UjjwalSharma01  please review and merge th PR  by today itself, so it consider as hactoberfest open source contribution

**Comment by kalkeshwar** [comment]
@UjjwalSharma01  please review and merge the PR . feel free to update reviews

**Comment by UjjwalSharma01** [comment]
Please improve this box correctly ASAP, i will merge it

**Comment by kalkeshwar** [comment]
@UjjwalSharma01 , your are telling that the checklist must be single line?

**Comment by UjjwalSharma01** [comment]
> @UjjwalSharma01 , your are telling that the checklist must be single line or the background color should be removed? 

Talking about the box around the txt

**Comment by kalkeshwar** [comment]
ok ! i will do it in 2 min and push those changes

**Comment by kalkeshwar** [comment]
@UjjwalSharma01 , please review and merge the PR as 12.00 passes.

thanks for having your time.

**Comment by kalkeshwar** [comment]
@UjjwalSharma01  please review and update about PR 
the hacktoberfest acceptance as closed in 2 min

**Review by UjjwalSharma01 — APPROVED** [review]

**Pull request merged**
