### PR TITLE
files added

### PR DESCRIPTION
**Pull request by Aqua-beast**
As for issue #23, these are final changes 
Screenshot 2023-10-25 212756
Screenshot 2023-10-25 212813
Screenshot 2023-10-25 212835
Screenshot 2023-10-25 212851

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
Button not working on clicking

Also always stays visible, it shouldn't be, it should only be visible after scrolling a bit

Also the fonts are not arranged properly

For the reference of back to top bottom you can check the example on codepen

**Comment by Aqua-beast** [comment]
Screenshot 2023-10-26 012514
Screenshot 2023-10-26 013050
in mobile devices i decided not to give the footer position fixed as it might cover the whole screen size available

**Comment by UjjwalSharma01** [comment]
image
again one more bug, the position is fixed in desktop mode

**Comment by UjjwalSharma01** [comment]
image
position is fixed in desktop mode

**Comment by Aqua-beast** [comment]
> codepen

Ohh i thought the second line always stay visible was meant for footer. But now i think you meant that for button. Okay understood, will update the changes.

**Pull request closed without merging**
