### PR TITLE
changes made to the code and footer component added

### PR DESCRIPTION
**Pull request by Aqua-beast**
As for issue #23, I have made the necessary changes adding the footer component with the necessary UI and adding a back-to-top button.
<br>
@UjjwalSharma01 review the changes 

Earlier 
Screenshot 2023-10-24 153215

After 
Screenshot 2023-10-25 004031

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
> As for issue #23, I have made the necessary changes adding the footer component with the necessary UI and adding a back-to-top button.
> <br>
> @UjjwalSharma01 review the changes 
> 
> 
> Earlier 
> Screenshot 2023-10-24 153215
> 
> After 
> Screenshot 2023-10-25 004031
> 
> 

Vercel is facing some issues, can't see the preview,so we have to wait for a while

**Comment by UjjwalSharma01** [comment]
Or the other thing we can do, jisss tumhari PR bhi affect na ho, just check and lemme know,  ki tumhare code ki vajah se koi aur functionality affect toh nahi hui h + responsiveness

**Comment by UjjwalSharma01** [comment]
In place of newsletter, add join our community

**Comment by Aqua-beast** [comment]
> Or the other thing we can do, jisss tumhari PR bhi affect na ho, just check and lemme know, ki tumhare code ki vajah se koi aur functionality affect toh nahi hui h + responsiveness

okay i can check that

**Comment by UjjwalSharma01** [comment]
Not responsive

**Comment by UjjwalSharma01** [comment]
And where the email addresses are being stored?

**Comment by Aqua-beast** [comment]
> And where the email addresses are being stored?

I could take care of the responsive design feature. But for storing data, that might not work as expected as i could implement a database but the admin will be me as my credentials will be used. And same goes for using nodemailer too. If you want, i can remove this and might add something else.

**Comment by Aqua-beast** [comment]
Screenshot 2023-10-25 174232
Screenshot 2023-10-25 174159

this is the change, if you like it let me know otherwise, i can revert this back to a subscription form

**Comment by UjjwalSharma01** [comment]
fair enough, just resolve the merge, conflict and you are good to go

**Comment by Aqua-beast** [comment]
> fair enough, just resolve the merge, conflict and you are good to go

i feel like these conflicts resolve are happening because some pull requests got accepted but the fork didn't sync due to which i have older version of repo. So, if you don't mind i will close this PR and create a new pr with required changes

**Pull request closed without merging**
