### PR TITLE
issue #151 done

### PR DESCRIPTION
**Pull request by 123shreyanvi**
Please do review it

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
Please resolve the issue highlighted in the screenshot mentioned above apart from this disable the property of hiding the blocks when we are scrolling upwards

**Comment by 123shreyanvi** [comment]
> 
> 
> Please resolve the issue highlighted in the screenshot mentioned above apart from this disable the property of hiding the blocks when we are scrolling upwards

I didn't understand, what are you  trying to say ?

**Comment by 123shreyanvi** [comment]
What is the issue with the arrow?

**Comment by 123shreyanvi** [comment]
> What is the issue with the arrow I didn't do anything there I have just put some animation on scroll? It's not hiding it's animation on scroll as U scroll the blocks will pop up

**Comment by 123shreyanvi** [comment]
Please check this i have made the changes.

**Review by UjjwalSharma01 — APPROVED** [review]

**Pull request merged**
