### PR TITLE
Website Made Responsive for all screens

### PR DESCRIPTION
**Pull request by Milind-Palaria**

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
image

increase the font size of the content in dropdown, as it's too small

**Comment by Milind-Palaria** [comment]
@UjjwalSharma01 sure i will do that , but can you merge this and i will create a new issue for that work, also you can tell something else you want. is it ok?

**Comment by UjjwalSharma01** [comment]
> @UjjwalSharma01 sure i will do that , but can you merge this and i will create a new issue for that work, also you can tell something else you want. is it ok?

replied to your issue, also fix the size of fields in contact us section, along with dark mode toggle button

**Comment by Milind-Palaria** [comment]
ok i will create a new pr with fixed issues

**Pull request closed without merging**
