### PR TITLE
UI Enhanced

### PR DESCRIPTION
**Pull request by Milind-Palaria**

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
When we scroll the screen 

Icon to toggle dark mode always stays on the top, it doesn't disappear as the screen moves

Please fix that

**Comment by UjjwalSharma01** [comment]
here are the screenshots for your reference 
image1

Image2

**Comment by Milind-Palaria** [comment]
@UjjwalSharma01 it was already like that but no problem i will change that. Give me a sec plz

**Comment by Milind-Palaria** [comment]
@UjjwalSharma01 can you check if this issue has a hacktoberfest label cause its not showing in the hacktober site

**Comment by UjjwalSharma01** [comment]
> @UjjwalSharma01 can you check if this issue has a hacktoberfest label cause its not showing in the hacktober site

Issue has but lemme add tag on this PR too don't worry it sometimes takes time, happened with me also

**Comment by Milind-Palaria** [comment]
@UjjwalSharma01 it got accepted just now.

**Comment by Milind-Palaria** [comment]
@UjjwalSharma01 can you merge this PR. I will make another issue for fixing the logo. is it ok with you? It will help me do more PRs

**Comment by UjjwalSharma01** [comment]
> @UjjwalSharma01 can you merge this PR. I will make another issue for fixing the logo. is it ok with you? It will help me do more PRs

Sure just a min plz

**Review by UjjwalSharma01 — APPROVED** [review]
great work

**Comment by UjjwalSharma01** [comment]
@Milind-Palaria you can create more issues now

**Pull request merged**
