### PR TITLE
Solution of issue #65

### PR DESCRIPTION
**Pull request by Panda-Abhisek**
Issue #65 
C Programming Notes added

Table of Contents:
Chapter 1: Introduction to C Programming
Chapter 2: Getting Started with C
Chapter 3: Control Structures
Chapter 4: Functions
Chapter 5: Arrays and Pointers
Chapter 6: Structures and Unions

Could you review the current PR and approve it?

I took references from my notes, google, w3schools, geeks for geeks, and tutorial points.

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
buddy hame issues aaege, png code ko optimise krne main, kisi aur tarike se store kr skte h aap ise, just like on gfg website

**Comment by Panda-Abhisek** [comment]
Is there any specific format in which I can convert these PNG images? 
Because GFG is storing their images in PNG formats.

**Comment by UjjwalSharma01** [comment]
image
this is not the PNG format buddy

**Comment by Panda-Abhisek** [comment]
Ok! Then I can convert these PNGs into JPG format.Sent from my Galaxy
-------- Original message --------From: Ujjwal Sharma ***@***.***> Date: 27/10/2023  2:47 am  (GMT+05:30) To: UjjwalSharma01/checklist ***@***.***> Cc: Abhisek_Panda ***@***.***>, Author ***@***.***> Subject: Re: [UjjwalSharma01/checklist] Solution of issue #65 (PR #103) 

this is not the PNG format buddy

**Comment by Panda-Abhisek** [comment]
Ok! I have converted the PNG images into JPG & WEBP formats. Which of these formats should I use on the website?

**Comment by UjjwalSharma01** [comment]
> Ok! I have converted the PNG images into JPG & WEBP formats. Which of these formats should I use on the website?

We just wanted the normal txt man, we cannot make the images or png or anything responsive in a better way

**Comment by Panda-Abhisek** [comment]
Sure! Then I'll start working on that. As soon as I get it done, I'll report you back.Sent from my Galaxy
-------- Original message --------From: Ujjwal Sharma ***@***.***> Date: 28/10/2023  11:46 pm  (GMT+05:30) To: UjjwalSharma01/checklist ***@***.***> Cc: Abhisek_Panda ***@***.***>, Author ***@***.***> Subject: Re: [UjjwalSharma01/checklist] Solution of issue #65 (PR #103) 

Ok! I have converted the PNG images into JPG & WEBP formats. Which of these formats should I use on the website?

We just wanted the normal txt man, we cannot make the images or png or anything responsive in a better way

**Pull request closed without merging**
