### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by arghadipmanna101**
- Update the photos.
- Added hover effect on "click here" buttons.
- By updating  CSS make it engaging.
- Update some colours combination.
- Added hover effect on some photos in contract us page.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
check the PR.

**Comment by UjjwalSharma01** [comment]
Please resolve these issues

**Comment by arghadipmanna101** [comment]
I already solved the problem.

image

**Comment by arghadipmanna101** [comment]
can you talk with me?

**Comment by UjjwalSharma01** [comment]
Alright DM me on discord @arghadipmanna101

**Comment by arghadipmanna101** [comment]
i send you a new PR you check out the PR.

**Comment by arghadipmanna101** [comment]
I think now in your website there is no issue.

**Pull request closed without merging**
