### PR TITLE
Added Frontend Projects folder

### PR DESCRIPTION
**Pull request by Vanraj8169**
Hey @UjjwalSharma01 
Issue No #109 

I have created new folders for front-end Projects. 
I have uploaded one of my frontend projects to it. 
It is a snake game with an interactive frontend UI. 
Please approve and give feedback. 
Thanking You!

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
Bhai kidhr add kya h?

**Comment by Vanraj8169** [comment]
Bhai woh folder add kiya hu na Front-end projects ka jisme projects upload karege sab

**Comment by UjjwalSharma01** [comment]
Usk folder ka access main site pe bhi do na bhai ese laise visible hoga vrna

**Comment by Vanraj8169** [comment]
Theek hai karta hu bhai

**Review by UjjwalSharma01 — APPROVED** [review]

**Pull request merged**
