### PR TITLE
new ui update

### PR DESCRIPTION
**Pull request by arghadipmanna101**
- Added hover effect on "contact us, contribute" buttons.
- Added hover effect on contact page pictures.
- and make the page engaging

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
check the pr once.

**Comment by UjjwalSharma01** [comment]
> check the pr once.
> 

Still the same issue

**Comment by arghadipmanna101** [comment]
can you join in google meet?

**Comment by UjjwalSharma01** [comment]
> can you join in google meet?
> 

Nope

**Comment by arghadipmanna101** [comment]
then can you join vc in discord?

**Comment by arghadipmanna101** [comment]
Screenshot 2024-01-20 215018


Screenshot 2024-01-20 215001

**Comment by UjjwalSharma01** [comment]
> Screenshot 2024-01-20 215018
> 
> 
> Screenshot 2024-01-20 215001
> 

Even in your mobile check yhe click here button

**Comment by UjjwalSharma01** [comment]
> then can you join vc in discord?
> 

Please state your problems

**Comment by UjjwalSharma01** [comment]
We don't have time, you are neither available on vc nor here? What to do?

**Review by UjjwalSharma01 — APPROVED** [review]

**Comment by arghadipmanna101** [comment]
Thank you

**Pull request closed without merging**
