### PR TITLE
add content in C++ Basics #4

### PR DESCRIPTION
**Pull request by Shrejal123**
i have add contents in c++.Please merge it .

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
In the section on Operators in C++, you have explained only arithmetic operators. It would be beneficial to include explanations of different data types such as int, float, bool, and char, as these are fundamental concepts. Additionally, it would be helpful to add information about the compilation process at the beginning. Apart from that, everything is good; your explanations are excellent for beginners

**Comment by Shrejal123** [comment]
I understand @UjjwalSharma01 . can i again to work on this issue?

**Comment by UjjwalSharma01** [comment]
yes you can make changes, and then push the changes, no issues in that, both request will be merged , but it will be counted as 1 PR on hactoberfest's dashboard

**Comment by Shrejal123** [comment]
@UjjwalSharma01 Please merge this pr

**Comment by UjjwalSharma01** [comment]
> @UjjwalSharma01 Please merge this pr as it is not showing accepted in my hactoberfest profile.

it is not showing accepted because it's not merged yet because, it needs improvement, we cannot merged half baked content

**Comment by Shrejal123** [comment]
Okay that it is compulsory for me to work again in this issue.please tell me

**Comment by UjjwalSharma01** [comment]
> Okay that it is compulsory for me to work again in this issue.please tell me

yes

**Comment by UjjwalSharma01** [comment]
@Shrejal123 you are working on this or should i close this PR?

**Comment by Shrejal123** [comment]
@UjjwalSharma01 you can assign it to other's.

**Pull request closed without merging**
