### PR TITLE
Add. Responsive Navbar

### PR DESCRIPTION
**Pull request by anu7701**

### CODE REVIEW

**Comment by anu7701** [comment]
Hey @UjjwalSharma01 i have made the nav bar responsive,
please review and merge it

**Comment by UjjwalSharma01** [comment]
loading Screenshot_2023-10-18-11-29-20-69_40deb401b9ffe8e1df2f1cc5ba480b12.jpg …]()

Fix these issues anu

**Comment by anu7701** [comment]
Can you please send the screenshots as attachments since the link is
not working and please elaborate the issue?

**Comment by UjjwalSharma01** [comment]
Screenshot_2023-10-18-11-29-20-69_40deb401b9ffe8e1df2f1cc5ba480b12
Screenshot_2023-10-18-11-28-45-57_40deb401b9ffe8e1df2f1cc5ba480b12


Fix these issues anu, and please mention the issue number with "hashtag" and for your reference im adding the screenshot of a website for your reference to make the changes

Screenshot (2054)
you can keep it like this, just add a button to close it in place of login section

also resolve the conflicts in the files, for any further issues or help you can reach out to us

**Pull request closed without merging**
