### PR TITLE
C Programming file added and basics contents added #65

### PR DESCRIPTION
**Pull request by Panda-Abhisek**
issue #65 
C Programming Notes added
Three chapters have been added up until this PR.
like:  What is C?
History of C
Why Learning C? / Benefits of Learning C language

More than three chapters will be added, so please do not close this issue.

codes and examples are coming along with my next PR.

Kindly review the current PR and approve it.

If there is any mistake or something to add up then tell me without any hesitation. I'll work on that and live up to your reputation.

### CODE REVIEW

**Comment by UjjwalSharma01** [comment]
we cannot accept the PRs just to increase the numbers as you have stated that you will be adding examples in next PR, it's against hacktober fests guidelines

**Comment by Panda-Abhisek** [comment]
ok then I have to complete the whole task first, then submit a PR ryt?
Ok! I'm working on it..

**Comment by Panda-Abhisek** [comment]
To update you @UjjwalSharma01, 
I have divided the basics of C Programming into a total number of 6 chapters.
3/6 chapters are done from my side, with proper definitions and explanations. 
I have added proper examples and code snippets to the documentation and the first Three chapters.

I want to take at least another two days to complete the rest Three chapters because they contain the following: 
* Functions
* Arrays & Pointers
* Structures & Unions
So, I want to take adequate time to document these topics.

**Comment by UjjwalSharma01** [comment]
Take your time

**Pull request closed without merging**
